version: "2.4"
services:
  python:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    image: hirota/python
    container_name: "python_hirota"
    env_file:
      - .env/main.env
    volumes:
      - "${HOME}/docsim:/workplace"
      - "${HOME}/docsim/docsim:/usr/local/lib/python3.8/site-packages/docsim:ro"
    networks:
      - docsim_default

  spm:
    build:
      dockerfile: Dockerfile.spm
      context: ./
    image: hirota/spm
    container_name: "spm_hirota"
    volumes:
      - "${HOME}/docsim:/workplace"
      - "${HOME}/docsim/docsim:/usr/local/lib/python3.8/site-packages/docsim:ro"
    networks:
      - docsim_default
    working_dir: /workplace 

  lsp:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    image: hirota/lsp
    container_name: "lsp_hirota"
    volumes:
      - "${HOME}/docsim:${HOME}/docsim"
      - "${HOME}/docsim/docsim:/usr/local/lib/python3.8/site-packages/docsim:ro"
    ports:
      - 11001:11001
    working_dir: "${HOME}/docsim"
    command: pyls --port 11001
    stdin_open: true


networks:
  docsim_default:
    external: true
