version: "3"
services:
  python:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    image: hirota/python
    container_name: "python_hirota"
    env_file:
      - .env/main.env
    networks:
      - docsim_default
    volumes:
      - "${HOME}/docsim:/workplace"
      - "${HOME}/docsim/docsim:/opt/conda/lib/python3.7/site-packages/docsim:ro"
      - "${HOME}/clef:/data/clef"
      - "${HOME}/ntcir:/data/ntcir"
      - "${HOME}/aan:/data/aan"

  lsp:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    image: hirota/lsp
    container_name: "lsp_hirota"
    volumes:
      - "${HOME}/docsim:${HOME}/docsim"
      - "${HOME}/docsim/docsim:/opt/conda/lib/python3.7/site-packages/docsim:ro"
    ports:
      - 11001:11001
    working_dir: "${HOME}/docsim"
    command: pyls --port 11001
    stdin_open: true

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
       - docsim_default

  broker:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
       - docsim_default

networks:
  docsim_default:
