FROM hirota/python

RUN apt-get update && apt-get install -y cmake build-essential pkg-config libgoogle-perftools-dev
RUN git clone https://github.com/google/sentencepiece.git /spm
WORKDIR /spm
RUN mkdir build
WORKDIR build
RUN cmake ../ && make -j $(nproc) && make install && ldconfig -v
