version: "2.4"
services:
  python:
    build:
      dockerfile: Dockerfile
      context: ./
    image: hirota/python
    container_name: "python_hirota"
    env_file:
      - .env/main.env
    volumes:
      - "${HOME}/docsim:/workplace"
      - "${HOME}/docsim/docsim:/opt/conda/lib/python3.7/site-packages/docsim:ro"
    networks:
      - docsim_default
  lsp:
    build:
      dockerfile: Dockerfile
      context: ./
    image: hirota/lsp
    container_name: "lsp_hirota"
    volumes:
      - "${HOME}/docsim:${HOME}/docsim"
      - "${HOME}/docsim/docsim:/opt/conda/lib/python3.7/site-packages/docsim:ro"
    ports:
      - 11001:11001
    working_dir: "${HOME}/docsim"
    command: pyls --port 11001
    stdin_open: true


networks:
  docsim_default:
    external: true
