version: "2.4"
services:
  lsp:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hirota/lsp
    container_name: "lsp_hirota"
    volumes:
      - /home/hirota/docsim:/home/hirota/docsim
    ports:
      - 11001:11001
    working_dir: /workplace
    command: pyls --port 11001
    stdin_open: true
