version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.1-hadoop2.7
    container_name: "spark_master_hirota"
    ports:
      - "18080:8080"
      - "17077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    container_name: "spark_worker_1_hirota"
    depends_on:
      - spark-master
    # ports:
    #   - "18081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==1"

  spark-worker-2:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    container_name: "spark_worker_2_hirota"
    depends_on:
      - spark-master
    # ports:
      # - "18082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==2"

