version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui
    ports:
      - "9090:9090"
  broker:
    image: qnib/plain-kafka:2019-01-28_2.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: '{{.Task.Slot}}'
