name: Test and Lint

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ES_URL: ""
      PROJECT_ROOT: ${GITHUB_WORKSPACE}

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
    - name: run tests
      run: bash run.bash test
    - name: run lint
      run: bash run.bash lint
