name: Test and Lint

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ES_URL: ""
      PROJECT_ROOT: ${GITHUB_WORKSPACE}

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
    - name: Create network
      run: docker network create docsim_default
    - name: run tests
      run: |
        docker-compose run -e IS_TEST=1 actions pytest docsim
    - name: run mypy
      run: |
        docker-compose run -e IS_TEST=1 actions mypy docsim
    - name: run flake8
      run: |
        docker-compose run -e IS_TEST=1 actions flake8 docsim
