name: Test and Lint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install sentencepiece
      run: |
        ENV SENTENCEPIECE_HOME ${GITHUB_WORKSPACE}/sentencepiece
        ENV PKG_CONFIG_PATH ${SENTENCEPIECE_HOME}/lib/pkgconfig
        RUN wget https://github.com/google/sentencepiece/archive/v0.1.84.zip && unzip v0.1.84.zip
        cd sentencepiece-0.1.84
        mkdir -p build
        cd ./bulid
        cmake -DCMAKE_INSTALL_PREFIX=${SENTENCEPIECE_HOME} ..  && make -j4 && make install
        cd ../python
        python setup.py install
    - name: Install dependencies
      run: |
        pip install numpy scipy Cython
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"
    - name: Tests
      run: make test
    - name: Lint with flake8
      run: make lint
