name: Docker Image CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
    - name: Tests
    - run: bash run.bash test
    - name: Lint
      run: bash run.bash lint
    
