name: unittests and lint

on:
  push:
    on:
      - develop
      - master

jobs:
  unittest:

    env:
      ES_URL: ""
      PROJECT_ROOT: ${GITHUB_WORKSPACE}
      NLPSERVER_URL: localhost

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
    - name: Create network
      run: docker network create docsim_default
    - name: Create network (nlpserver)
      run: docker network create nlpserver_default
    - name: run tests
      run: |
        docker-compose run -e IS_TEST=1 -e NLPSERVER_URL=${NLPSERVER_URL} actions pytest docsim

  mypy:

    env:
      ES_URL: ""
      PROJECT_ROOT: ${GITHUB_WORKSPACE}
      NLPSERVER_URL: localhost

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker-compose build
    - name: Create network
      run: docker network create docsim_default
    - name: Create network (nlpserver)
      run: docker network create nlpserver_default
    - name: run mypy
      run: |
        docker-compose run -e IS_TEST=1 actions mypy docsim
